[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
kamabla = "DdZtiP97GwpatRNrw82yzSQwXKiGnhY6pMvKtbJJ5Qcv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=6c738364-a484-43f1-a755-7c29134b0cdf"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
